config/routes.rb
MultitenancyExample::Application.routes.draw do

  devise_for :users do
    post  "users" => "devise/custom/registrations#create"
  end

  resources :comments
  resources :blogs, :only => [:index, :show]

  resources :blogs do
    resources :posts, :only => [:index, :show]
  end
  
  namespace :admin do
    resources :posts, :except => :show
    get "settings", :to => 'settings#edit', :as => "edit_settings"
    put "settings", :to => 'settings#update', :as => "update_settings"
  end

  root :to => 'static#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_tenant
  attr_accessible :body, :title
  belongs_to :blog
  has_many :comments
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_posts_path, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to admin_posts_path, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_filter :authenticate_user!

  def index
    @posts = Post.all
    @blog = current_user.blog
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])
    @blog = current_user.blog
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %> or <%= link_to "Cancel", admin_posts_path %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/admin/posts/index.html.erb
<%= render "admin/shared/header" %>

<div id="maincontent">
<%= link_to "+ New Post", new_admin_post_path, :class => 'button'%> 
<br />
<br />
<% if @posts.empty? %>
  <b>Oops! no posts by the author yet!</b>
<% else %>
  <% @posts.each do |post| %>
    <div class="post">
      <b><%= post.title %></b>
      <p><%= post.body %></p>
      <p><%= link_to 'View Post', blog_post_path(current_user.blog, post), :target => "_blank"%> | <%= link_to 'Edit', edit_admin_post_path(post) %> | <%= link_to 'Destroy', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>
  <% end %>
<% end %>

</div>

app/views/admin/posts/new.html.erb
<%= render "admin/shared/header" %>

<div id="maincontent">
  <b>New post</b>
  <br /><br />

  <%= render 'form' %>

</div>