config/routes.rb
MultitenancyExample::Application.routes.draw do

  devise_for :users do
    post  "users" => "devise/custom/registrations#create"
  end

  resources :comments
  resources :blogs, :only => [:index, :show]

  resources :blogs do
    resources :posts, :only => [:index, :show]
  end
  
  namespace :admin do
    resources :posts, :except => :show
    get "settings", :to => 'settings#edit', :as => "edit_settings"
    put "settings", :to => 'settings#update', :as => "update_settings"
  end

  root :to => 'static#index'

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    p "params ~~~> #{params.inspect}"
    @user = User.find(params[:user][:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_edit_settings_path, notice: 'Blog settings was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/views/admin/settings/edit.html.erb
<%= render "admin/shared/header" %>

<div id="maincontent">
  <b>Blog Settings</b>
  <br/><br/>

  <%= nested_form_for @user, :url => admin_update_settings_path  do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this blog settings from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.hidden_field :id, :value => @user.id %>
    <%= f.fields_for :blog do |blog_form| %>
      <div class="field">
        <%= blog_form.label :blog_name %><br />
        <%= blog_form.text_field :name %>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :your_name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :twitter_url %><br />
      <%= f.text_field :twitter_url %>
    </div>
    <div class="field">
      <%= f.label :github_url %><br />
      <%= f.text_field :github_url %>
    </div>

    <div class="actions">
      <%= f.submit %> or <%= link_to "Cancel", admin_posts_path %>
    </div>
  <% end %>

</div>

app/views/admin/settings/update.html.erb
<h1>Admin::Settings#update</h1>
<p>Find me in app/views/admin/settings/update.html.erb</p>