config/routes.rb
MultitenancyExample::Application.routes.draw do

  devise_for :users do
    post  "users" => "devise/custom/registrations#create"
  end

  resources :comments
  resources :blogs, :only => [:index, :show]

  resources :blogs do
    resources :posts, :only => [:index, :show]
  end
  
  namespace :admin do
    resources :posts, :except => :show
    get "settings", :to => 'settings#edit', :as => "edit_settings"
    put "settings", :to => 'settings#update', :as => "update_settings"
  end

  root :to => 'static#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_tenant
  attr_accessible :body, :title
  belongs_to :blog
  has_many :comments
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_posts_path, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to admin_posts_path, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_filter :authenticate_user!

  def index
    @posts = Post.all
    @blog = current_user.blog
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])
    @blog = current_user.blog
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div>
  <div id='headeractions' >
    <div>
      <b style="font-size: 14px;"><%= @blog.name %></b>
    </div>
    <div>
      <b style="font-size: small;">[by <%= @blog.user.name || 'anonymous' %>]</b>&nbsp;&nbsp;&nbsp;
      <%= link_to "All Posts", blog_posts_path(@blog) %> &nbsp;&nbsp;&nbsp;
      <% unless @blog.user.github_url.blank? %>
        <%= link_to "github", "#{@blog.user.github_url}" %> &nbsp;&nbsp;&nbsp;
      <% end %>
      <% unless @blog.user.github_url.blank? %>
        <%= link_to "twitter", "#{@blog.user.twitter_url}" %> &nbsp;&nbsp;&nbsp;
      <% end %>
      <% if current_user %>
        <b id="admin">[<%= link_to "Your Admin Dashboard", admin_posts_path %>]</b>
      <% end %>
    </div>
  </div>
</div>


<div id="maincontent">
  <% unless @posts.empty? %>
    <% @posts.each do |post| %>
    <div class="post">
      <h3><%= link_to post.title, blog_post_path(@blog, post) %></h3>
      <p style="font-size: small; color: #898989; ">updated on <%= post.created_at.to_s %></p>
      <br />
    </div>
    <% end %>
  <% else %>
  <b>Oops! no posts found! </b>
  <% end %>
</div>

app/views/posts/show.html.erb
<div>
  <div id='headeractions' >
    <div>
      <b style="font-size: 14px;"><%= @blog.name %></b>
    </div>
    <div>
      <b style="font-size: small;">[by <%= @blog.user.name || 'anonymous' %>]</b>&nbsp;&nbsp;&nbsp;
      <%= link_to "All Posts", blog_posts_path(@blog) %> &nbsp;&nbsp;&nbsp;
      <% unless @blog.user.github_url.blank? %>
        <%= link_to "github", "#{@blog.user.github_url}" %> &nbsp;&nbsp;&nbsp;
      <% end %>
      <% unless @blog.user.github_url.blank? %>
        <%= link_to "twitter", "#{@blog.user.twitter_url}" %> &nbsp;&nbsp;&nbsp;
      <% end %>
      <% if current_user %>
        <b id="admin">[<%= link_to "Your Admin Dashboard", admin_posts_path %>]</b>
      <% end %>
    </div>
  </div>
</div>


<div id="maincontent">
  <h3><%= @post.title %></h3>
  <p style="font-size: small; color: #898989; ">updated on <%= @post.created_at.to_s %></p>
  <br />

  <p>
    <%= @post.body %>
  </p>

</div>